---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: "another-"
  annotations:
    pipelinesascode.tekton.dev/target-namespace: "pac-e2e-ns-sbc4f"
    pipelinesascode.tekton.dev/on-target-branch: "[pac-e2e-ns-sbc4f]"
    pipelinesascode.tekton.dev/on-event: "[incoming]"
spec:
  pipelineSpec:
    tasks:
      - name: task
        taskSpec:
          steps:
            - name: task
              image: registry.access.redhat.com/ubi9/ubi-micro
              command: ["/bin/echo", "HELLOMOTO"]
